


print("-------------------------	S e t	M e t h o d s	  -------------------------------------")

myset={'apple','banana','mango','orange'}
print("")
print("myset={'apple','banana','mango','orange'}")
print("")
print(myset)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("accessing items of myset through looping")
print("")
for x in myset:
	print(x)

print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print("print('banana' in myset) - it just check that the particular item is belong to the set or not")
print("")
print("banana" in myset)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print("myset.add('strawberry') - it adds new element in the set")
print("")
myset.add("strawberry")
print("")
print(myset)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print("myset.update(['car','bike','scooter']) - it use to add multiple item at once in the set")
print("")
myset.update(['car','bike','scooter'])	
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print("print(len(myset)) - it use to print length of set")
print("")
print(len(myset))
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print("myset.remove('banana') - it use to remove item from set but gives error if element is not present in set")
print("")
myset.remove('banana')
print(myset)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print("myset.discard('banana') - it also use to remove element but not gives error if element is not present")
print("")
myset.discard('banana')
print(myset)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print("print(myset(pop)) - it use to print or remove last item from set but as we know set is unordered so it pop up any random value")
print("")
print(myset.pop())
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print("myset.copy for copying")
x=myset.copy()
print("")
print(x)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print('Using subset function:- checks subset:-')
c={'a','b','c'}
e={'f','e','d','c','b','a'}
l=c.issubset(e)
print(l)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print('Using union function:-')
z=myset.union(e)
print(z)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print('using difference dfunctions')
y={'google','yahoo','apple'}
z=myset.difference(y)
print(z)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print("")
print('Using discard function to remove item')
myset.discard('strawberry')
print(myset)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print('Using intersection function:-')
z=myset.intersection(y)
print(z)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print('Using intersection update function:-')
z=myset.intersection_update(y)
print(z)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")
print("myset.clear() - it removes all elements from the set")
myset.clear()
print("")
print(myset)
print("")
print("")
print("_________________________________________________________________________")

print("")
print("")

