a=('apple','grapes','mango')
print(a)
print('---------------------------------------------------------------------')
print('Returning items at various positions=')
print(a[0])
print(a[1])
print(a[2])
print(a[-1])
print(a[-2])
print(a[0])
print('---------------------------------------------------------------------')
print('using for loop')
for i in a:
	print(i)
print('---------------------------------------------------------------------')
print('checking if item exist in tuple using if loop')
if 'grapes' in a:
	print('yes')
print('---------------------------------------------------------------------')
print('checking tuple length:')
print(len(a))
print('---------------------------------------------------------------------')
print('cannot add or remove item to tuple')
print('---------------------------------------------------------------------')
print('counting the number of times the values occurs:')
x=a.count('mango')
print(x)
print('---------------------------------------------------------------------')
print('searching the value and returning the index')
x=a.index('apple')
print(x)
print('---------------------------------------------------------------------')
