print("####################		S e t	M e t h o d s	  ######################")
print('by Parvinder Singh')
print("_________________________________________________________________________")
print("set is collection of elements which is unordered as well as unindexed and written with curly brackets'{}'")
print("set are unordered so they print in random order")
print("we cant access element of sets by indexing because they are unordered but we can loop through them" )
print("once a set is defined we cant change its elements but we can add more items to it")
print("_________________________________________________________________________________")
myset={'apple','banana','mango','orange'}
print("")
print("myset={'apple','banana','mango','orange'}")
print("")
print(myset)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("accessing items of myset through looping")
print("")
for x in myset:
	print(x)

print("")
print("")
print("")
print("")
print("print('banana' in myset) - it just check that the particular item is belong to the set or not")
print("")
print("banana" in myset)
print("")
print("")
print("")
print("")
print("myset.add('strawberry') - it adds new element in the set")
print("")
myset.add("strawberry")
print("")
print(myset)
print("")
print("")
print("")
print("")
print("myset.update(['car','bike','scooter']) - it use to add multiple item at once in the set")
print("")
myset.update(['car','bike','scooter'])	
print("")
print("")
print("")
print("")
print("print(len(myset)) - it use to print length of set")
print("")
print(len(myset))
print("")
print("")
print("")
print("")
print("myset.remove('banana') - it use to remove item from set but gives error if element is not present in set")
print("")
myset.remove('banana')
print(myset)
print("")
print("")
print("")
print("")
print("myset.discard('banana') - it also use to remove element but not gives error if element is not present")
print("")
myset.discard('banana')
print(myset)
print("")
print("")
print("")
print("")
print("print(myset(pop)) - it use to print or remove last item from set but as we know set is unordered so it pop up any random value")
print("")
print(myset.pop())
print("")
print("")
print("")
print("")
print("myset.copy for copying")
x=myset.copy()
print("")
print(x)
print("")
print("")
print("")
print("")
print('Using subset function:- checks subset:-')
c={'a','b','c'}
e={'f','e','d','c','b','a'}
l=c.issubset(e)
print(l)
print("")
print("")
print("")
print("")
print('Using union function:-')
z=myset.union(e)
print(z)
print("")
print("")
print("")
print("")
print('using difference dfunctions')
y={'google','yahoo','apple'}
z=myset.difference(y)
print(z)
print("")
print("")
print("")
print("")
print("")
print('Using discard function to remove item')
myset.discard('strawberry')
print(myset)
print("")
print("")
print("")
print("")
print('Using intersection function:-')
z=myset.intersection(y)
print(z)
print("")
print("")
print("")
print("")
print('Using intersection update function:-')
z=myset.intersection_update(y)
print(z)
print("")
print("")
print("")
print("")
print("myset.clear() - it removes all elements from the set")
myset.clear()
print("")
print(myset)
print("")
print("")
print("")
print("")

