car=('bmw','audi','porche')
print(car)
print('---------------------------------------------------------------------')
print('Returning item at various positions')
print(car[0])
print(car[1])
print(car[2])
print(car[-1])
print(car[-2])
print(car[0])
print('---------------------------------------------------------------------')
print('using for loop')
for x in car:
	print(x)
print('---------------------------------------------------------------------')
print('checking if item exist in tuple using if loop')
if 'bmw' in car:
	print('yes')
print('---------------------------------------------------------------------')
print('checking tuple length:-')
print(len(car))
print('---------------------------------------------------------------------')
print('cannot add or remove item to tuple')
print('---------------------------------------------------------------------')
#print('Tuple Constructor:-')
#car=car1(('bmw','audi','porche'))
#print(car1)
#print('---------------------------------------------------------------------')
print('counting the number of times the values occurs:-')
x=car.count('bmw')
print(x)
print('---------------------------------------------------------------------')
print('searching the value and returning the index')
x=car.index('porche')
print(x)
print('---------------------------------------------------------------------')
#car.add('mercedes')
#print(car)
#print('---------------------------------------------------------------------')
