print("#################	L  i  s  t		M  e  t  h  o  d  s	   ####################")
print("________________________________________________________________________________")
print("")
print("mylist=['kirti','deshwal',9,4.7]")
print("mylist1=['BMW','AUDI','MARUTI','HONDA']")
print("")
print("________________________________________________________________________________")

mylist=['kirti','deshwal',9,4.7]
print("list.append('guddu') - it adds new element to the list")
print("")
mylist.append('guddu')
print("")

print(mylist)
print("")
print("________________________________________________________________________________")
print("mylist.clear() - it removes all elements from the list")
print("")
mylist.clear()
print(mylist)
print("")
print("________________________________________________________________________________")
print("mylist.count('kirti') - it counts the number of specific elements int the list")
print("")
print(mylist.count("kirti"))
mylist=['kirti','deshwal',9,4.7]
print("")
print("________________________________________________________________________________")
print("mylist.copy - it makes a copy of original list")
print("")
print(mylist.copy())
print("________________________________________________________________________________")
mylist1=['BMW','AUDI','MARUTI','HONDA']
mylist.append('guddu')
print("")
print("mylist.extend(mylist1) - it will concatinate both the list")
print("")
mylist.extend(mylist1)
print(mylist)
print("")
print("________________________________________________________________________________")
print("mylist1.index('BMW') - it prints the index of particular element in list")
print("")
print(mylist1.index("BMW"))
print("")
print("________________________________________________________________________________")
print("mylist.insert(1,'parm') - it add new element at desired position of list")
mylist.insert(1,'parm')
print(mylist)
print("________________________________________________________________________________")
print("")
print("list.pop(3) - it removes specifies indexed element of the list ")
mylist.pop()
print(mylist)

print("")
print("________________________________________________________________________________")
print("mylist.remove('kirti') - it removes specific element from list")
mylist.remove('kirti')
print(mylist)
print("")
print("________________________________________________________________________________")
print("mylist1.sort() - it sorts the list")
print("")
mylist1.sort()
print(mylist1)
print("________________________________________________________________________________")
print("formating")
print("")
print("first {0},second is {1}, third is {2}".format(mylist1[1],mylist1[2],mylist1[0]))
print("")
print("________________________________________________________________________________")
print("mylist.everse() - it prints the string in reverse order")
mylist.reverse()
print(mylist)
