print("##################	T u p l e	M e t h o d s	####################")
print("_____________________________________________________________________")
print("")
print("Tuple are like list in python but they are odered and unchangable")
print("We can't change, add, remove, replace any element in tuple")
print("")
tuple=('apple','banana','mango','strawberry')
print("tuple=('apple','banana','mango','strawberry')")
print("")
print(tuple)

print("")
print("")
print("_____________________________________________________________________")
print("print(tuple[1]) - it use to access particular indexed element in tuple ")
print("")
print(tuple[1])
print("")
print("")
print("_____________________________________________________________________")
print("accessing tuple through tuple")
print("")
for x in tuple:
	print(x)

print("")
print("")
print("_____________________________________________________________________")
print("to check that element is present in the tuple or not")
print("if 'apple' in tuple than print yes apple is present")
print("")
if 'apple' in tuple:
	print("yes apple is present in the tuple")

print("")
print("")
print("_____________________________________________________________________")
print("print(len(tuple)) - it prints the length of the tuple")
print("")
print(len(tuple))
print("")
print("")
print("_____________________________________________________________________")
print("print(tuple.index('banana')) - it returns the index of particular element of the tuple")
print("")
print(tuple.index('banana'))
print("")
print("")
print("_____________________________________________________________________")
print("print(tuple.count('mango')) - it returns that how many times a particular element is coming in tuple")
print("")
print(tuple.count('mango'))
print("_____________________________________________________________________")




