print("####################		S e t	M e t h o d s	  ######################")
print("_________________________________________________________________________")
print("set is collection of elements which is unordered as well as unindexed and written with curly brackets'{}'")
print("set are unordered so they print in random order")
print("we cant access element of sets by indexing because they are unordered but we can loop through them" )
print("once a set is defined we cant change its elements but we can add more items to it")
print("_________________________________________________________________________________")
myset={'apple','banana','mango','orange'}
print("")
print("myset={'apple','banana','mango','orange'}")
print("")
print(myset)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("accessing items of myset through looping")
print("")
for x in myset:
	print(x)

print("")
print("")
print("_________________________________________________________________________________")
print("")
print("print('banana' in myset) - it just check that the particular item is belong to the set or not")
print("")
print("banana" in myset)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("myset.add('strawberry') - it adds new element in the set")
print("")
myset.add("strawberry")
print("")
print(myset)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("myset.update(['car','bike','scooter']) - it use to add multiple item at once in the set")
print("")
myset.update(['car','bike','scooter'])	
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("print(len(myset)) - it use to print length of set")
print("")
print(len(myset))
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("myset.remove('banana') - it use to remove item from set but gives error if element is not present in set")
print("")
myset.remove('banana')
print(myset)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("myset.discard('banana') - it also use to remove element but not gives error if element is not present")
print("")
myset.discard('banana')
print(myset)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("print(myset(pop)) - it use to print or remove last item from set but as we know set is unordered so it pop up any random value")
print("")
print(myset.pop())
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("myset.clear() - it removes all elements from the set")
myset.clear()
print("")
print(myset)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("del myset - it use to delete set completely")
myset1={'A','b','C','d'}
myset2={'A','z','X','y'}
print("myset1={'A','b','C','d'}")
print("")
print("_________________________________________________________________________________")
print("x=myset1.copy() - it copy set into varable x")
print("")
x=myset1.copy()
print(x)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("z=myset1.difference(myset2) - it stores the value if set1 - set2 in it")
z=myset1.difference(myset2)
print("")
print(z)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("myset1.difference_update(myset2) - it just remove that element from set 1 which is common in both")
print("")
print("_________________________________________________________________________________")
print("z=myset1.intersection(myset2) - it just stores common values to z")
print("")
print("_________________________________________________________________________________")
print("myset1.instersection_update(myset2) - it just removes all elements from set 1 that are not common in both set")
print("")
print("_________________________________________________________________________________")
print("z=myset1.isdisjoint(myset2) - z will return true if both set contains some common values else returns false")
z=myset1.isdisjoint(myset2)
print(z)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("z=myset1.issubset(myset2) - z will return true if set1 is subset of set2 else returns false")
print("")
print("_________________________________________________________________________________")
print("z=myset1.issuperset(myset2) - z will return true if set1 is superset of set2 else returns false")
print("")
print("_________________________________________________________________________________")
print("z = myset1.symmetric_difference(myset2) - z will store all those values which are not common in both sets ")
z = myset1.symmetric_difference(myset2)
print("")
print(z)
print("")
print("")
print("_________________________________________________________________________________")
print("")
print("myset1.symmetric_difference_update(myset2) - set1 will store all those values which are not common in both sets ")





